extends Resource
class_name FC_FeagiEndpointDetails
## Describes the details of the FEAGI endpoint, used to intiiate a connection
# NOTE: DO NOT EDIT THIS FILE TO CHANGE DEFAULTS! Instead look in the Config folder

@export var header: PackedStringArray = ["Content-Type: application/json"] # this is likely constant, so define this
@export var feagi_tld: StringName
@export var API_port: int
@export var websocket_port: int
@export var is_encrypted: bool

func get_api_URL() -> StringName:
	if is_encrypted:
		return "https://" + feagi_tld + ":" + str(API_port)
	return "http://" + feagi_tld + ":" + str(API_port)
	
func get_websocket_URL() -> StringName:
	if is_encrypted:
		return "wss://" + feagi_tld + ":" + str(websocket_port)
	return "ws://" + feagi_tld + ":" + str(websocket_port)
	
