extends GenomeObject
class_name AbstractCorticalArea
## Holds details pertaining to a specific cortical area
## Should not be instantiated directly

# Main functionality for cortical area, and base details such as ID, name, and positions
#region Base Functionality

const TYPES_NOT_ALLOWED_TO_BE_MOVED_INTO_SUBREGION: Array[CORTICAL_AREA_TYPE] = [
	CORTICAL_AREA_TYPE.IPU,
	CORTICAL_AREA_TYPE.OPU,
	CORTICAL_AREA_TYPE.CORE,
]

## The type of cortical area, not 1-1 mapped with feagi
enum CORTICAL_AREA_TYPE {
	IPU,
	CORE,
	MEMORY,
	CUSTOM,
	INTERCONNECT,
	OPU,
	UNKNOWN
}

## Any specific flags to be aware of for a cortical area? 
enum CORTICAL_FLAGS {
	EACH_AFFERENT_CONNECTION_MAX_ONE_MAPPING,
	EACH_EFFERENT_CONNECTION_MAX_ONE_MAPPING
}

signal cortical_visibility_updated(visibility: bool, this_cortical_area: AbstractCorticalArea)
signal cortical_neuron_per_vox_count_updated(density: int, this_cortical_area: AbstractCorticalArea)
signal cortical_synaptic_attractivity_updated(attractivity: int, this_cortical_area: AbstractCorticalArea)
signal changed_monitoring_membrane_potential(is_monitoring: bool)
signal changed_monitoring_synaptic_potential(is_monitoring: bool)
signal recieved_new_neuron_activation_data(activation_SVO_data: PackedByteArray) ## Contains only the SVO structure byte data, not the headers!
signal recieved_new_direct_neural_points(points_data: PackedByteArray) ## Contains direct neural points data for optimized rendering
signal recieved_new_direct_neural_points_bulk(x_array: PackedInt32Array, y_array: PackedInt32Array, z_array: PackedInt32Array, p_array: PackedFloat32Array) ## Contains bulk arrays for ultra-optimized rendering

# Desktop-only visualization fast-path registration (WebSocket -> Rust GDExtension -> MultiMesh)
# Stored here to avoid tight coupling between FEAGI networking and Brain Monitor scene instances.
var _bv_directpoints_renderer: Object = null
var _bv_directpoints_multimesh: MultiMesh = null
var _bv_directpoints_dimensions: Vector3 = Vector3.ZERO


## Unique identifier of the cortical area, generated by FEAGI
var cortical_ID: StringName:
	get: return _genome_ID



## DEPRECATED: The base type of cortical area as understood by FEAGI (use feagi_cortical_type instead)
var cortical_type: CORTICAL_AREA_TYPE:
	get:  return _get_group()

## NEW: Strongly-typed cortical type from Rust (single source of truth)
var feagi_cortical_type: FeagiCorticalType:
	get: return _feagi_cortical_type
	set(value):
		_feagi_cortical_type = value

var type_as_string: StringName:
	get: return AbstractCorticalArea.cortical_type_to_str(_get_group())

var _feagi_cortical_type: FeagiCorticalType  # NEW - single source of truth

## IPU/OPU-specific decoded cortical ID fields (only populated for IPU/OPU areas)
var cortical_subtype: String:
	get: return _cortical_subtype

var encoding_type: String:
	get: return _encoding_type

var encoding_format: String:
	get: return _encoding_format

## Cortical subunit index (which area within a cortical unit, e.g., segment 0-4 for isvi)
var unit_id: int:
	get: return _unit_id

## Cortical unit index (which unit of this type, encoded in byte 7 of cortical ID)
## This identifies which instance of a cortical unit type (e.g., unit 0, unit 1, etc.)
var group_id: int:
	get: return _group_id

## IO coding signage (e.g., "Percentage Signed", "Percentage Unsigned")
var coding_signage: String:
	get: return _coding_signage

## IO coding behavior ("Absolute" or "Incremental")
var coding_behavior: String:
	get: return _coding_behavior

## IO coding type ("Linear" or "Fractional")
var coding_type: String:
	get: return _coding_type

## Allowed IO coding signage options (for dropdowns)
var coding_signage_options: Array[StringName]:
	get: return _coding_signage_options

## Allowed IO coding behavior options (for dropdowns)
var coding_behavior_options: Array[StringName]:
	get: return _coding_behavior_options

## Allowed IO coding type options (for dropdowns)
var coding_type_options: Array[StringName]:
	get: return _coding_type_options

var has_decoded_id_info: bool:
	get: return _cortical_subtype != ""

## Is cortical area activity visible?
var cortical_visibility: bool:
	get: return _cortical_visiblity

var cortical_neuron_per_vox_count: int:
	get: return _cortical_neuron_per_vox_count

var cortical_synaptic_attractivity: int:
	get: return _cortical_synaptic_attractivity

var SVO_neuron_activations: PackedByteArray:
	get: return _SVO_neuron_activations

var direct_neural_points: PackedByteArray:
	get: return _direct_neural_points

var neuron_count: int:
	get: return AbstractCorticalArea.get_neuron_count(_dimensions_3D, _cortical_neuron_per_vox_count)

## Visualization voxel granularity for large-area rendering (x, y, z)
## If set, this area uses aggregated rendering instead of individual neuron rendering
## null = normal rendering, Vector3i = aggregated rendering mode with granularity dimensions
var visualization_voxel_granularity: Vector3i:
	get: 
		# Default is 1x1x1 if not set or if somehow 0,0,0 (should never happen)
		if _visualization_voxel_granularity == Vector3i.ZERO:
			return Vector3i(1, 1, 1)
		return _visualization_voxel_granularity

var are_details_placeholder_data: bool = true ## We don't have the true values for details yet

## Has a 2D location been specified in FEAGI yet or is still unknown?
var is_coordinates_2D_available: bool:
	get:  return _coordinates_2D_available

## Has a 3D location been specified in FEAGI yet or is still unknown?
var is_coordinates_3D_available: bool:
	get:  return _coordinates_3D_available

## Can a user edit the name of this cortical area?
var user_can_edit_name: bool:
	get: return _user_can_edit_name()

## Can a user edit the dimensions of this cortical area?
var user_can_edit_dimensions_directly: bool:
	get: return _user_can_edit_dimensions_directly()

## Can a user edit the dimensions of this cortical area?
var user_can_delete_this_area: bool:
	get: return _user_can_delete_area()

var user_can_edit_cortical_neuron_per_vox_count: bool:
	get: return _user_can_edit_cortical_neuron_per_vox_count()

var user_can_edit_cortical_synaptic_attractivity: bool:
	get: return _user_can_edit_cortical_synaptic_attractivity()

var user_can_clone_this_cortical_area: bool:
	get: return _user_can_clone_this_area()

var can_exist_in_subregion: bool:
	get: return !(cortical_type in TYPES_NOT_ALLOWED_TO_BE_MOVED_INTO_SUBREGION)
	#get: return _area_can_exist_in_subregion()

var has_neuron_firing_parameters: bool:
	get:  return _has_neuron_firing_parameters()

var has_memory_parameters: bool:
	get: return _has_memory_parameters()

# Private Properties
var _cortical_neuron_per_vox_count: int = 1
var _cortical_synaptic_attractivity: int = 100
var _coordinates_2D_available: bool = false  # if coordinates_2D are available from FEAGI
var _coordinates_3D_available: bool = false  # if coordinates_3D are available from FEAGI
var _cortical_visiblity: bool = true
var _SVO_neuron_activations: PackedByteArray = []
var _direct_neural_points: PackedByteArray = []

# IPU/OPU-specific decoded cortical ID fields (empty strings if not IPU/OPU)
var _cortical_subtype: String = ""
var _encoding_type: String = ""
var _encoding_format: String = ""
var _unit_id: int = -1
var _group_id: int = -1
var _coding_signage: String = ""
var _coding_behavior: String = ""
var _coding_type: String = ""
var _coding_signage_options: Array[StringName] = []
var _coding_behavior_options: Array[StringName] = []
var _coding_type_options: Array[StringName] = []

# Visualization voxel granularity for large-area rendering (default is 1x1x1)
var _visualization_voxel_granularity: Vector3i = Vector3i(1, 1, 1)  # Default is 1x1x1

static func do_cortical_areas_have_matching_values_for_property(areas: Array[AbstractCorticalArea], composition_section_name: StringName, property_name: StringName) -> bool:
	var differences: int = -1 # first one will always fail
	var previous_value: Variant = null
	var current_value: Variant = null
	#TODO for vectors, to have per element diffs, branch out from here
	for area in areas:
		current_value = area.return_property_by_name_and_section(composition_section_name, property_name)
		if current_value == null:
			return false # if the property doesnt exist
		if previous_value != current_value:
			differences += 1
			if differences > 0:
				# Differences
				return false
			previous_value = current_value
		continue
	# If we got here, values are identical
	return true

## Array of Cortical Areas to Array of Cortical IDs
static func cortical_area_array_to_ID_array(arr: Array[AbstractCorticalArea]) -> Array[StringName]:
	var output: Array[StringName] = []
	for area: AbstractCorticalArea in arr:
		output.append(area.cortical_ID)
	return output

## From a string of cortical type, returns the cortical type enum
static func cortical_type_str_to_type(cortical_type_raw: String) -> CORTICAL_AREA_TYPE:
	cortical_type_raw = cortical_type_raw.to_upper()
	if cortical_type_raw in CORTICAL_AREA_TYPE.keys():
		return CORTICAL_AREA_TYPE[cortical_type_raw]
	else:
		push_error("Unknown Cortical Type " + cortical_type_raw +". Marking as INVALID!")
		return CORTICAL_AREA_TYPE.UNKNOWN

## From a human readable string of cortical type, to cortical type enum
static func cortical_type_human_readable_str_to_type(cortical_type_raw: String) -> CORTICAL_AREA_TYPE:
	cortical_type_raw = cortical_type_raw.to_lower()
	match(cortical_type_raw):
		"input":
			return CORTICAL_AREA_TYPE.IPU
		"output":
			return CORTICAL_AREA_TYPE.OPU
		"core":
			return CORTICAL_AREA_TYPE.CORE
		"interconnect":
			return CORTICAL_AREA_TYPE.INTERCONNECT
		"memory":
			return CORTICAL_AREA_TYPE.MEMORY
		_:
			return CORTICAL_AREA_TYPE.UNKNOWN

## Filters through a GenomeObject array to output only [AbstractCorticalArea]s
static func genome_array_to_cortical_area_array(genome_objects: Array[GenomeObject]) -> Array[AbstractCorticalArea]:
	var output: Array[AbstractCorticalArea] = []
	for genome in genome_objects:
		if genome is AbstractCorticalArea:
			output.append(genome)
	return output

## If any of the given cortical areas are of a type specified, returns true
static func array_contains_cortical_area_of_types(areas: Array[AbstractCorticalArea], types: Array[AbstractCorticalArea.CORTICAL_AREA_TYPE]) -> bool:
	for area in areas:
		if area.cortical_type in types:
			return true
	return false

## Returns true only if all given cortical areas can be allowed in subregions
static func can_all_areas_exist_in_subregion(areas: Array[AbstractCorticalArea]) -> bool:
	for area in areas:
		if !area.can_exist_in_subregion:
			return false
	return true

static func can_all_areas_be_deleted(areas: Array[AbstractCorticalArea]) -> bool:
	for area in areas:
		if !area.user_can_delete_this_area:
			return false
	return true

## Given a cortical type enum, return the string
static func cortical_type_to_str(cortical_type: CORTICAL_AREA_TYPE) -> StringName:
	return CORTICAL_AREA_TYPE.keys()[cortical_type]

static func get_neuron_count(dimensions: Vector3i, density: float) -> int:
	return int(float(dimensions.x * dimensions.y * dimensions.z) * density)

## Check if a cortical_ID (in old 6-char or new base64 format) is a special core area
## Returns the core area name if it matches, or empty string if not
static func get_special_core_area_name(cortical_id: String) -> String:
	# Dictionary mapping both old and new formats to their canonical names
	# CRITICAL: Uses feagi-data-processing format (3 prefix underscores: ___power, ___death)
	const SPECIAL_CORE_AREAS = {
		# Power area (legacy formats)
		"_power": "power",
		"_power__": "power",
		"X3Bvd2VyX18=": "power",  # base64 of "_power__" (OLD format)
		
		# Power area (NEW format from feagi-data-processing)
		"___power": "power",
		"X19fcG93ZXI=": "power",  # base64 of "___power" (NEW format)
		
		# Death area (legacy formats)
		"_death": "death",
		"_death__": "death",
		"X2RlYXRoX18=": "death",  # base64 of "_death__" (OLD format)
		
		# Death area (NEW format from feagi-data-processing)
		"___death": "death",
		"X19fZGVhdGg=": "death",  # base64 of "___death" (NEW format)
	}
	
	return SPECIAL_CORE_AREAS.get(cortical_id, "")

## Check if a cortical_ID is the power area (supports both old and new formats)
static func is_power_area(cortical_id: String) -> bool:
	return get_special_core_area_name(cortical_id) == "power"

## Check if a cortical_ID is the death area (supports both old and new formats)
static func is_death_area(cortical_id: String) -> bool:
	return get_special_core_area_name(cortical_id) == "death"

static func array_of_cortical_areas_to_array_of_cortical_IDs(arr: Array[AbstractCorticalArea]) -> Array[StringName]:
	var output: Array[StringName] = []
	for e in arr:
		output.append(e.cortical_ID)
	return output

## If all cortical areas in an array are of the same type, return that type enum, otherwise return CORTICAL_AREA_TYPE.UNKNOWN
static func array_oc_cortical_areas_type_identification(areas: Array[AbstractCorticalArea]) -> CORTICAL_AREA_TYPE:
	if len(areas) == 0:
		return CORTICAL_AREA_TYPE.UNKNOWN
	var comparison: CORTICAL_AREA_TYPE = areas[0].cortical_type
	if len(areas) == 1:
		return comparison
	for i in range(1, len(areas)):
		if areas[i].cortical_type != comparison:
			return CORTICAL_AREA_TYPE.UNKNOWN
	return comparison

## If given a boolean property, returns true if all areas have this property true. otherwise, returns false, and returns false if property is invalid
static func boolean_property_of_all_cortical_areas_are_true(areas: Array[AbstractCorticalArea], property: StringName) -> bool:
	for area in areas:
		if area.get(property) == null:
			return false
		if area.get(property) != true:
			return false
	return true

## DO NOT init this object directly! use a subclass!
func _init(ID: StringName, cortical_name: StringName, cortical_dimensions: Vector3i, parent_region: BrainRegion, visiblity: bool = true):
	_genome_ID = ID
	_friendly_name = cortical_name
	_dimensions_3D = cortical_dimensions
	_cortical_visiblity = visiblity
	_init_self_to_brain_region(parent_region)


## Called from [CorticalAreasCache] when cortical area is being deleted
func FEAGI_delete_cortical_area() -> void:
	#NOTE: Assumption is made that connections were already removed firstZ!
	print("🗑️ FEAGI_delete_cortical_area: About to emit about_to_be_deleted for %s" % cortical_ID)
	_parent_region.FEAGI_genome_object_deregister_as_child(self)
	about_to_be_deleted.emit()
	print("🗑️ FEAGI_delete_cortical_area: Emitted about_to_be_deleted for %s" % cortical_ID)
	# [CorticalAreasCache] then deletes this object

## Helper function to safely convert dimensions data that might be Array or Dictionary
func _safe_convert_to_vector3i(data: Variant, field_name: String = "") -> Vector3i:
	if data is Array:
		return FEAGIUtils.array_to_vector3i(data)
	elif data is Dictionary:
		var dict_data: Dictionary = data as Dictionary
		# Handle common dictionary formats for 3D coordinates
		if dict_data.has("x") and dict_data.has("y") and dict_data.has("z"):
			return Vector3i(int(dict_data["x"]), int(dict_data["y"]), int(dict_data["z"]))
		elif dict_data.has("width") and dict_data.has("height") and dict_data.has("depth"):
			return Vector3i(int(dict_data["width"]), int(dict_data["height"]), int(dict_data["depth"]))
		else:
			push_error("ABSTRACT CORTICAL AREA: Unsupported dictionary format for %s: %s" % [field_name, str(dict_data)])
			return Vector3i(1, 1, 1)  # Default fallback
	else:
		push_error("ABSTRACT CORTICAL AREA: Unsupported data type for %s: %s" % [field_name, str(type_string(typeof(data)))])
		return Vector3i(1, 1, 1)  # Default fallback

## Helper function to safely convert 2D coordinate data that might be Array or Dictionary  
func _safe_convert_to_vector2i(data: Variant, field_name: String = "") -> Vector2i:
	if data is Array:
		return FEAGIUtils.array_to_vector2i(data)
	elif data is Dictionary:
		var dict_data: Dictionary = data as Dictionary
		# Handle common dictionary formats for 2D coordinates
		if dict_data.has("x") and dict_data.has("y"):
			return Vector2i(int(dict_data["x"]), int(dict_data["y"]))
		elif dict_data.has("width") and dict_data.has("height"):
			return Vector2i(int(dict_data["width"]), int(dict_data["height"]))
		else:
			push_error("ABSTRACT CORTICAL AREA: Unsupported dictionary format for %s: %s" % [field_name, str(dict_data)])
			return Vector2i(0, 0)  # Default fallback
	else:
		push_error("ABSTRACT CORTICAL AREA: Unsupported data type for %s: %s" % [field_name, str(type_string(typeof(data)))])
		return Vector2i(0, 0)  # Default fallback

## Applies every detail from the dictionary from FEAGI
func FEAGI_apply_full_dictionary(data: Dictionary) -> void:
	if data == {}:
		return
	if "cortical_id" not in data.keys():
		push_error("Input dictionary to update cortical area %s is invalid! Skipping!" % _genome_ID)
		return
	if data["cortical_id"] != _genome_ID:
		push_error("Input dictionary to update cortical area %s has sent to %s! Skipping!" % [data["cortical_id"], _genome_ID])
		return
	
	if "cortical_name" in data.keys():
		FEAGI_change_friendly_name(data["cortical_name"])
	if "cortical_visibility" in data.keys():
		FEAGI_set_cortical_visibility(data["cortical_visibility"])
	if "cortical_dimensions" in data.keys():
		FEAGI_change_dimensions_3D(_safe_convert_to_vector3i(data["cortical_dimensions"], "cortical_dimensions"))
	
	if "coordinates_2d" in data.keys():
		var coords_2d_data = data["coordinates_2d"]
		# Handle both array and dictionary formats for checking if coordinates are defined
		if coords_2d_data is Array:
			if coords_2d_data[0] == null:
				_coordinates_2D_available = false
			else:
				FEAGI_change_coordinates_2D(_safe_convert_to_vector2i(coords_2d_data, "coordinates_2d"))
		elif coords_2d_data is Dictionary:
			# If it's a dictionary, assume coordinates are defined unless explicitly null
			if coords_2d_data != null and coords_2d_data.size() > 0:
				FEAGI_change_coordinates_2D(_safe_convert_to_vector2i(coords_2d_data, "coordinates_2d"))
			else:
				_coordinates_2D_available = false
		else:
			if coords_2d_data == null:
				_coordinates_2D_available = false
			else:
				FEAGI_change_coordinates_2D(_safe_convert_to_vector2i(coords_2d_data, "coordinates_2d"))

	if "coordinates_3d" in data.keys():
		if data["coordinates_3d"] == null:
			_coordinates_3D_available = false
		else:
			FEAGI_change_coordinates_3D(_safe_convert_to_vector3i(data["coordinates_3d"], "coordinates_3d"))
	
	# Visualization voxel granularity - default is 1x1x1 if not present or null
	if "visualization_voxel_granularity" in data.keys():
		var value = data["visualization_voxel_granularity"]
		print("🔵 CACHE: Processing visualization_voxel_granularity for %s: value=%s, type=%s" % [cortical_ID, value, typeof(value)])
		if value != null:
			# Handle array format [x, y, z] from API (tuple serializes as array in JSON)
			# Value can be int or float, so convert to float first then int
			if value is Array and value.size() == 3:
				var x = int(float(value[0])) if value[0] != null else 1
				var y = int(float(value[1])) if value[1] != null else 1
				var z = int(float(value[2])) if value[2] != null else 1
				# Treat 0,0,0 as default (1,1,1) - API might return 0,0,0 for default
				if x == 0 and y == 0 and z == 0:
					_visualization_voxel_granularity = Vector3i(1, 1, 1)
					print("🔵 CACHE: Converted 0,0,0 to default 1,1,1 for %s" % cortical_ID)
				else:
					_visualization_voxel_granularity = Vector3i(x, y, z)
					print("🔵 CACHE: Set visualization_voxel_granularity to %s for %s" % [_visualization_voxel_granularity, cortical_ID])
			# Handle dictionary format {"x": x, "y": y, "z": z} (backup)
			elif value is Dictionary and value.has("x") and value.has("y") and value.has("z"):
				var x = int(float(value["x"])) if value["x"] != null else 1
				var y = int(float(value["y"])) if value["y"] != null else 1
				var z = int(float(value["z"])) if value["z"] != null else 1
				_visualization_voxel_granularity = Vector3i(x, y, z)
			else:
				_visualization_voxel_granularity = Vector3i(1, 1, 1)  # Default
		else:
			_visualization_voxel_granularity = Vector3i(1, 1, 1)  # Default
	else:
		# Field not present in response - default is 1x1x1
		_visualization_voxel_granularity = Vector3i(1, 1, 1)
	
	if "parent_region_id" in data.keys():
		if !(data["parent_region_id"] in FeagiCore.feagi_local_cache.brain_regions.available_brain_regions):
			push_error("Unable to find new region ID %s for cortical area %s" % [data["parent_region_id"], cortical_ID])
			return
		var new_region: BrainRegion = FeagiCore.feagi_local_cache.brain_regions.available_brain_regions[data["parent_region_id"]]
		if new_region != current_parent_region:
			FEAGI_change_parent_brain_region(new_region)

			

	FEAGI_apply_detail_dictionary(data)

# NOTE: This function applies all details (but not base information such as name, visibility, dimensions or positions), and may be expanded in other cortical types
## Updates all cortical details in here from a dict from FEAGI
func FEAGI_apply_detail_dictionary(data: Dictionary) -> void:
	
	are_details_placeholder_data = false # Assuming if ANY data is updated here, that all data here is not placeholders
	
	# NEW: Extract FeagiCorticalType if present
	if "_feagi_cortical_type" in data.keys():
		var feagi_type = data["_feagi_cortical_type"]
		if feagi_type is FeagiCorticalType:
			_feagi_cortical_type = feagi_type
	
	# Cortical Parameters
	if "cortical_neuron_per_vox_count" in data.keys(): 
		var value = data["cortical_neuron_per_vox_count"]
		if value != null:
			_cortical_neuron_per_vox_count = int(value)
			cortical_neuron_per_vox_count_updated.emit(_cortical_neuron_per_vox_count, self)
	# Also support "neurons_per_voxel" key from API responses
	if "neurons_per_voxel" in data.keys():
		var value = data["neurons_per_voxel"]
		if value != null:
			_cortical_neuron_per_vox_count = int(value)
			cortical_neuron_per_vox_count_updated.emit(_cortical_neuron_per_vox_count, self)
	if "cortical_synaptic_attractivity" in data.keys(): 
		var value = data["cortical_synaptic_attractivity"]
		if value != null:
			_cortical_synaptic_attractivity = int(value)
			cortical_synaptic_attractivity_updated.emit(_cortical_synaptic_attractivity, self)
	
	# IPU/OPU-specific decoded cortical ID fields
	if "cortical_subtype" in data.keys():
		var value = data["cortical_subtype"]
		if value != null:
			_cortical_subtype = value
	
	if "encoding_type" in data.keys():
		var value = data["encoding_type"]
		if value != null:
			_encoding_type = value
	
	if "encoding_format" in data.keys():
		var value = data["encoding_format"]
		if value != null:
			_encoding_format = value
	
	if "unit_id" in data.keys():
		var value = data["unit_id"]
		if value != null:
			_unit_id = int(value)
	
	if "group_id" in data.keys():
		var value = data["group_id"]
		if value != null:
			_group_id = int(value)

	if "coding_signage" in data.keys():
		var value = data["coding_signage"]
		if value != null:
			_coding_signage = String(value)

	if "coding_behavior" in data.keys():
		var value = data["coding_behavior"]
		if value != null:
			_coding_behavior = String(value)

	if "coding_type" in data.keys():
		var value = data["coding_type"]
		if value != null:
			_coding_type = String(value)

	if "coding_signage_options" in data.keys():
		var value = data["coding_signage_options"]
		if value is Array:
			var options: Array[StringName] = []
			for item in value:
				options.append(StringName(str(item)))
			_coding_signage_options = options

	if "coding_behavior_options" in data.keys():
		var value = data["coding_behavior_options"]
		if value is Array:
			var options: Array[StringName] = []
			for item in value:
				options.append(StringName(str(item)))
			_coding_behavior_options = options

	if "coding_type_options" in data.keys():
		var value = data["coding_type_options"]
		if value is Array:
			var options: Array[StringName] = []
			for item in value:
				options.append(StringName(str(item)))
			_coding_type_options = options

	if "coding_options" in data.keys():
		var value = data["coding_options"]
		if value is Dictionary:
			if value.has("signage_options") and value["signage_options"] is Array:
				var options: Array[StringName] = []
				for item in value["signage_options"]:
					options.append(StringName(str(item)))
				_coding_signage_options = options
			if value.has("behavior_options") and value["behavior_options"] is Array:
				var options: Array[StringName] = []
				for item in value["behavior_options"]:
					options.append(StringName(str(item)))
				_coding_behavior_options = options
			if value.has("coding_type_options") and value["coding_type_options"] is Array:
				var options: Array[StringName] = []
				for item in value["coding_type_options"]:
					options.append(StringName(str(item)))
				_coding_type_options = options
	
	if _coding_signage_options.is_empty() and (_coding_behavior_options.size() > 0 or _coding_type_options.size() > 0):
		print("BV [NEURAL-CODING][CACHE]: Missing signage_options for %s; behavior_opts=%d type_opts=%d" % [
			cortical_ID,
			_coding_behavior_options.size(),
			_coding_type_options.size()
		])
	
	# Visualization voxel granularity for large-area rendering (also handled in FEAGI_apply_full_dictionary for updates)
	# Visualization voxel granularity - default is 1x1x1 if not present or null
	if "visualization_voxel_granularity" in data.keys():
		var value = data["visualization_voxel_granularity"]
		print("🔵 CACHE: Processing visualization_voxel_granularity for %s: value=%s, type=%s" % [cortical_ID, value, typeof(value)])
		if value != null:
			# Handle array format [x, y, z] from API (tuple serializes as array in JSON)
			# Value can be int or float, so convert to float first then int
			if value is Array and value.size() == 3:
				var x = int(float(value[0])) if value[0] != null else 1
				var y = int(float(value[1])) if value[1] != null else 1
				var z = int(float(value[2])) if value[2] != null else 1
				# Treat 0,0,0 as default (1,1,1) - API might return 0,0,0 for default
				if x == 0 and y == 0 and z == 0:
					_visualization_voxel_granularity = Vector3i(1, 1, 1)
					print("🔵 CACHE: Converted 0,0,0 to default 1,1,1 for %s" % cortical_ID)
				else:
					_visualization_voxel_granularity = Vector3i(x, y, z)
					print("🔵 CACHE: Set visualization_voxel_granularity to %s for %s" % [_visualization_voxel_granularity, cortical_ID])
			# Handle dictionary format {"x": x, "y": y, "z": z} (backup)
			elif value is Dictionary and value.has("x") and value.has("y") and value.has("z"):
				var x = int(float(value["x"])) if value["x"] != null else 1
				var y = int(float(value["y"])) if value["y"] != null else 1
				var z = int(float(value["z"])) if value["z"] != null else 1
				_visualization_voxel_granularity = Vector3i(x, y, z)
			else:
				_visualization_voxel_granularity = Vector3i(1, 1, 1)  # Default
		else:
			_visualization_voxel_granularity = Vector3i(1, 1, 1)  # Default
	else:
		# Field not present in response - default is 1x1x1
		_visualization_voxel_granularity = Vector3i(1, 1, 1)
	
	post_synaptic_potential_paramamters.FEAGI_apply_detail_dictionary(data)

	return

func FEAGI_set_cortical_visibility(is_visible: bool) -> void:
	if is_visible == _cortical_visiblity:
		return
	_cortical_visiblity = is_visible
	cortical_visibility_updated.emit(_cortical_visiblity, self)

func FEAGI_set_cortical_neuron_per_vox_count(new_density: int) -> void:
	if new_density == _cortical_neuron_per_vox_count:
		return
	_cortical_neuron_per_vox_count = new_density
	cortical_neuron_per_vox_count_updated.emit(new_density, self)

func FEAGI_set_SVO_visualization_data(SVO_byte_structure: PackedByteArray) -> void:
	_SVO_neuron_activations = SVO_byte_structure
	recieved_new_neuron_activation_data.emit(SVO_byte_structure)

func FEAGI_set_direct_points_visualization_data(points_data: PackedByteArray) -> void:
	_direct_neural_points = points_data
	recieved_new_direct_neural_points.emit(points_data)

func FEAGI_set_direct_points_bulk_data(x_array: PackedInt32Array, y_array: PackedInt32Array, z_array: PackedInt32Array, p_array: PackedFloat32Array) -> void:
	"""Set direct neural points data using bulk arrays for ultra-optimized processing"""
	# Store arrays directly for future reference (if needed)
	# Note: We could store these in dedicated variables if needed for caching
	recieved_new_direct_neural_points_bulk.emit(x_array, y_array, z_array, p_array)

## Brain Visualizer: register DirectPoints renderer resources for the desktop WS fast-path.
## This enables FEAGIWebSocketAPI to apply neuron visualization directly to GPU instancing (MultiMesh)
## without routing through per-area signals and bulk arrays.
func BV_register_directpoints_renderer(renderer: Object, multimesh: MultiMesh, dimensions: Vector3) -> void:
	_bv_directpoints_renderer = renderer
	_bv_directpoints_multimesh = multimesh
	_bv_directpoints_dimensions = dimensions

## Brain Visualizer: unregister DirectPoints renderer resources (scene teardown).
func BV_unregister_directpoints_renderer() -> void:
	_bv_directpoints_renderer = null
	_bv_directpoints_multimesh = null
	_bv_directpoints_dimensions = Vector3.ZERO

## Brain Visualizer: retrieve registered MultiMesh for fast-path rendering (may be null if not registered/visible).
func BV_get_directpoints_multimesh() -> MultiMesh:
	return _bv_directpoints_multimesh

## Brain Visualizer: retrieve registered dimensions for fast-path rendering.
func BV_get_directpoints_dimensions() -> Vector3:
	return _bv_directpoints_dimensions

## Brain Visualizer: lightweight activity notification for renderer side-effects (timers/animations).
## Note: fast-path rendering updates the MultiMesh directly; this is only for behavior parity.
func BV_notify_directpoints_activity(point_count: int) -> void:
	if _bv_directpoints_renderer != null and _bv_directpoints_renderer.has_method("bv_notify_activity"):
		_bv_directpoints_renderer.call("bv_notify_activity", point_count)

## Brain Visualizer: refresh DirectPoints renderer visuals when cortical properties change.
## This is critical for the desktop Type11 WS fast-path because it bypasses per-area bulk signals.
func BV_refresh_directpoints_renderer_visuals() -> void:
	if _bv_directpoints_renderer != null and _bv_directpoints_renderer.has_method("_refresh_visualization_voxel_granularity_from_cache"):
		_bv_directpoints_renderer.call("_refresh_visualization_voxel_granularity_from_cache")

func FEAGI_set_no_visualizeation_data() -> void:
	if len(_SVO_neuron_activations) != 7:
		_SVO_neuron_activations = PackedByteArray([1,0,1,0, 0 ,255,255,255])
		recieved_new_neuron_activation_data.emit(_SVO_neuron_activations)
	# Clear direct points data as well
	if len(_direct_neural_points) != 0:
		_direct_neural_points = PackedByteArray()
		recieved_new_direct_neural_points.emit(_direct_neural_points)

func FEAGI_set_cortical_synaptic_attractivity(new_attractivity: int) -> void:
	if new_attractivity == _cortical_synaptic_attractivity:
		return
	_cortical_synaptic_attractivity = new_attractivity
	cortical_synaptic_attractivity_updated.emit(new_attractivity, self)

func get_neuron_change_with_new_details(new_dimension: Vector3i, new_density: float) -> int:
	return AbstractCorticalArea.get_neuron_count(new_dimension, new_density) - neuron_count

## Returns the value of a property (optionally within a section). returns null if nonexistant
func return_property_by_name_and_section(composition_section_name: StringName, property_name: StringName) -> Variant:
	var section_object: RefCounted = null
	if composition_section_name != "":
		section_object = get(composition_section_name) # Assumption is that all cortical areas in the selected array have the section
		if section_object == null:
			return null # if the section doesnt exist
		return section_object.get(property_name)
	else:
		# For properties on self, access directly (get() doesn't work with custom getters)
		# Handle common properties that have custom getters
		if property_name == "visualization_voxel_granularity":
			return visualization_voxel_granularity
		elif property_name == "dimensions_3D":
			return dimensions_3D
		elif property_name == "coordinates_3D":
			return coordinates_3D
		else:
			# Try get() for other properties
			return get(property_name)

# The following functions are often overridden in child classes
func _get_group() -> CORTICAL_AREA_TYPE:
	## OVERRIDE THIS
	return CORTICAL_AREA_TYPE.UNKNOWN

func _user_can_edit_dimensions_directly() -> bool:
	return true

func _user_can_edit_name() -> bool:
	return true

func _user_can_delete_area() -> bool:
	return true

func _user_can_edit_cortical_neuron_per_vox_count() -> bool:
	return true

func _user_can_edit_cortical_synaptic_attractivity() -> bool:
	return true

func _user_can_clone_this_area() -> bool:
	return false

func _has_neuron_firing_parameters() -> bool:
	return false

func _has_memory_parameters() -> bool:
	return false

#endregion


# Functionality and references to how this cortical area is mapped / connected to other cortical areas / regions
#region Mapping

# NOTE: While we have connection links for pathing information for HOW connections are made to other objects, we 
# also have this to know WHAT we are connecting to, because sometimes we don't care about partial connections or regions

signal afferent_input_cortical_area_added(area: AbstractCorticalArea, mapping_set: InterCorticalMappingSet)
signal efferent_input_cortical_area_added(area: AbstractCorticalArea, mapping_set: InterCorticalMappingSet)
signal recursive_cortical_area_added(area: AbstractCorticalArea, mapping_set: InterCorticalMappingSet)
signal afferent_input_cortical_area_removed(area: AbstractCorticalArea, mapping_set: InterCorticalMappingSet)
signal efferent_input_cortical_area_removed(area: AbstractCorticalArea, mapping_set: InterCorticalMappingSet)
signal recursive_cortical_area_removed(area: AbstractCorticalArea, mapping_set: InterCorticalMappingSet)

var afferent_mappings: Dictionary: # Key'd by the source [AbstractCorticalArea] object, value is the related [InterCorticalMappingSet]
	get: return _afferent_mappings
var efferent_mappings: Dictionary: # Key'd by the destination [AbstractCorticalArea] object, value is the related [InterCorticalMappingSet]
	get: return _efferent_mappings
var recursive_mappings: Dictionary: # Key'd by the (self) [AbstractCorticalArea] object, value is the related [InterCorticalMappingSet]
	get: return _recursive_mappings

var _afferent_mappings: Dictionary = {}
var _efferent_mappings: Dictionary = {}
var _recursive_mappings: Dictionary = {} # technically, this will only be of size 0 or 1 lol

## Called by [InterCorticalMappingSet] during its init
func CACHE_mapping_set_register_an_afferent(mapping_set: InterCorticalMappingSet) -> void:
	_afferent_mappings[mapping_set.source_cortical_area] = mapping_set
	afferent_input_cortical_area_added.emit(mapping_set.source_cortical_area, mapping_set)

## Called by [InterCorticalMappingSet] during its init
func CACHE_mapping_set_register_an_efferent(mapping_set: InterCorticalMappingSet) -> void:
	_efferent_mappings[mapping_set.destination_cortical_area] = mapping_set
	efferent_input_cortical_area_added.emit(mapping_set.destination_cortical_area, mapping_set)

## Called by [InterCorticalMappingSet] during its init
func CACHE_mapping_set_register_a_recursive(mapping_set: InterCorticalMappingSet) -> void:
	_recursive_mappings[mapping_set.destination_cortical_area] = mapping_set
	recursive_cortical_area_added.emit(mapping_set.destination_cortical_area, mapping_set)

## Called by [InterCorticalMappingSet] during its init
func CACHE_mapping_set_deregister_an_afferent(mapping_set: InterCorticalMappingSet) -> void:
	_afferent_mappings.erase(mapping_set.source_cortical_area)
	afferent_input_cortical_area_removed.emit(mapping_set.source_cortical_area, mapping_set)

## Called by [InterCorticalMappingSet] during its init
func CACHE_mapping_set_deregister_an_efferent(mapping_set: InterCorticalMappingSet) -> void:
	_efferent_mappings.erase(mapping_set.destination_cortical_area)
	efferent_input_cortical_area_removed.emit(mapping_set.destination_cortical_area, mapping_set)

## Called by [InterCorticalMappingSet] during its init
func CACHE_mapping_set_deregister_a_rescursive(mapping_set: InterCorticalMappingSet) -> void:
	_recursive_mappings.erase(mapping_set.source_cortical_area)
	recursive_cortical_area_removed.emit(mapping_set.source_cortical_area, mapping_set)

func get_mapping_array_toward_cortical_area(destination: AbstractCorticalArea) -> Array[SingleMappingDefinition]:
	if destination in _efferent_mappings:
		return _efferent_mappings[destination].mappings
	if destination in _recursive_mappings:
		return _recursive_mappings[destination].mappings
	# no mapping exists between these areas, return an empty array!
	return []

#endregion

#region Post Synaptic Potential Parameters

## Holds all post synaptic potential paramamters
var post_synaptic_potential_paramamters: CorticalPropertyPostSynapticPotentialParameters = CorticalPropertyPostSynapticPotentialParameters.new(self)
#endregion

# Monitoring settings for this specific cortical area
#region Monitoring Settings
var is_monitoring_membrane_potential: bool
var is_monitoring_synaptic_potential: bool
#endregion
