extends RefCounted
class_name SingleMappingDefinition
## A single mapping definition (IE morphology used and properties).
## NOTE: This object is generated a lot in memory as a form of passing data, not only as a reference in cache!
## WARNING: In the cache, this object is routinely thrown out and regenerated by [InterCorticalMappingSet], beware of storing this object from Feagi Cache by reference!

const DEFAULT_POSITIVE_SCALAR: Vector3i = Vector3i(1,1,1)
const DEFAULT_PSP_MULTIPLIER: float = 1.0
const DEFAULT_PLASTICITY: bool = false
const DEFAULT_PLASTICITY_CONSTANT: float = 1.0
const DEFAULT_LTP_MULTIPLIER: float = 1.0
const DEFAULT_LTD_MULTIPLIER: float = 1.0
const DEFAULT_PLASTICITY_WINDOW: int = 3
## Whole bursts from presynaptic fire until PSP is applied (minimum 1; genome / API key: synaptic_delay_bursts).
const DEFAULT_SYNAPTIC_DELAY_BURSTS: int = 1


## Resolve morphology for a mapping rule. IDs may be human-readable or autogenerated (e.g. voxel
## QuickConnect in [WindowQuickConnectNeuron] uses source_cortical_ID + "_" + destination_cortical_ID,
## which looks like base64 fragments but is a valid morphology name).
static func _get_cached_morphology_for_mapping_rule(morph_id: Variant) -> BaseMorphology:
	var m: BaseMorphology = FeagiCore.feagi_local_cache.morphologies.try_get_morphology_by_ambiguous_key(
		morph_id
	)
	if m != null:
		return m
	push_warning(
		"SingleMappingDefinition: Skipping rule — morphology '%s' not in cache (reload morphologies or check FEAGI morphologies list)"
		% morph_id
	)
	return null


var morphology_used: BaseMorphology:
	get: return _morphology_used
var scalar: Vector3i:
	get: return _scalar
var is_plastic: bool:
	get: return _plasticity_flag
var post_synaptic_current_multiplier: float:
	get: return _post_synaptic_current_multiplier
var plasticity_constant: float:
	get: return _plasticity_constant
var LTP_multiplier: float:
	get: return _LTP_multiplier
var LTD_multiplier: float:
	get: return _LTD_multiplier
var plasticity_window: int:
	get: return _plasticity_window
var synaptic_delay_bursts: int:
	get: return _synaptic_delay_bursts
## Plasticity mode string: "off" | "stdp" | "rstdp" (empty when genome doesn't specify)
var plasticity_mode: String:
	get: return _plasticity_mode
## Decay time constant (in bursts) for the eligibility trace under R-STDP. 0 means no temporal credit.
var eligibility_decay_bursts: int:
	get: return _eligibility_decay_bursts
## Base64 cortical_id of the area whose density drives positive R(t) (empty when not configured)
var reward_source_area: String:
	get: return _reward_source_area
## Base64 cortical_id of the area whose density drives negative R(t) (empty when not configured)
var punishment_source_area: String:
	get: return _punishment_source_area
## True iff this rule has any reward/punishment source declared (used by BV for tap rendering)
var has_reward_modulation: bool:
	get: return _reward_source_area != "" or _punishment_source_area != ""

var _morphology_used: BaseMorphology
var _scalar: Vector3i # must all be non-zero positive
var _post_synaptic_current_multiplier: float
var _plasticity_flag: bool
var _plasticity_constant: float
var _LTP_multiplier: float
var _LTD_multiplier: float
var _plasticity_window: int
var _synaptic_delay_bursts: int
var _plasticity_mode: String = ""
var _eligibility_decay_bursts: int = 0
var _reward_source_area: String = ""
var _punishment_source_area: String = ""

## Creates a mapping with default settings (given a morphology)
static func create_default_mapping(morphology: BaseMorphology) -> SingleMappingDefinition:
	var plasticity_enabled: bool = DEFAULT_PLASTICITY
	if morphology != null and morphology.name == &"associative_memory":
		plasticity_enabled = true
	return SingleMappingDefinition.new(
		morphology,
		DEFAULT_POSITIVE_SCALAR,
		DEFAULT_PSP_MULTIPLIER,
		plasticity_enabled
	)

## Helper function to safely convert dimensions data that might be Array or Dictionary
static func _safe_convert_to_vector3i(data: Variant, field_name: String = "") -> Vector3i:
	if data is int:
		return Vector3i(int(data), int(data), int(data))
	if data is float:
		var s := int(data)
		return Vector3i(s, s, s)
	if data is Array:
		return FEAGIUtils.array_to_vector3i(data)
	elif data is Dictionary:
		var dict_data: Dictionary = data as Dictionary
		# Handle common dictionary formats for 3D coordinates
		if dict_data.has("x") and dict_data.has("y") and dict_data.has("z"):
			return Vector3i(int(dict_data["x"]), int(dict_data["y"]), int(dict_data["z"]))
		elif dict_data.has("width") and dict_data.has("height") and dict_data.has("depth"):
			return Vector3i(int(dict_data["width"]), int(dict_data["height"]), int(dict_data["depth"]))
		else:
			push_error("SINGLE MAPPING DEFINITION: Unsupported dictionary format for %s: %s" % [field_name, str(dict_data)])
			return Vector3i(1, 1, 1)  # Default fallback
	else:
		push_error("SINGLE MAPPING DEFINITION: Unsupported data type for %s: %s" % [field_name, str(type_string(typeof(data)))])
		return Vector3i(1, 1, 1)  # Default fallback

## Legacy row format from connectome / cortical_map_detailed (matches feagi-api cortical_mapping normalization):
## [morphology_id, morphology_scalar, postSynapticCurrent_multiplier, plasticity_flag,
##  plasticity_constant, ltp_multiplier, ltd_multiplier, plasticity_window, synaptic_delay_bursts]
static func _from_FEAGI_JSON_array_rule(rule: Array) -> SingleMappingDefinition:
	if rule.size() < 4:
		push_error("SingleMappingDefinition: array mapping rule needs at least 4 elements, got %d" % rule.size())
		return null
	var morphology_cached: BaseMorphology = _get_cached_morphology_for_mapping_rule(rule[0])
	if morphology_cached == null:
		return null
	var scalar_used: Vector3i = _safe_convert_to_vector3i(rule[1], "morphology_scalar")
	var psp_multiplier: float = float(rule[2])
	var plasticity: bool = bool(rule[3])
	if morphology_cached.name == &"associative_memory":
		plasticity = true
	var delay_from_rule: int = DEFAULT_SYNAPTIC_DELAY_BURSTS
	if rule.size() >= 9:
		delay_from_rule = maxi(1, int(rule[8]))
	if !plasticity:
		return SingleMappingDefinition.new(
			morphology_cached,
			scalar_used,
			psp_multiplier,
			plasticity,
			DEFAULT_PLASTICITY_CONSTANT,
			DEFAULT_LTP_MULTIPLIER,
			DEFAULT_LTD_MULTIPLIER,
			DEFAULT_PLASTICITY_WINDOW,
			delay_from_rule,
		)
	var plasticity_constant_used: float = DEFAULT_PLASTICITY_CONSTANT
	var LTP_multiplier_used: float = DEFAULT_LTP_MULTIPLIER
	var LTD_multiplier_used: float = DEFAULT_LTD_MULTIPLIER
	var plasticity_window_used: int = DEFAULT_PLASTICITY_WINDOW
	if rule.size() >= 8:
		plasticity_constant_used = float(rule[4])
		LTP_multiplier_used = float(rule[5])
		LTD_multiplier_used = float(rule[6])
		plasticity_window_used = int(rule[7])
	else:
		push_error("FEAGI CORE: Plasticity mapping in array format with fewer than 8 elements; using defaults for plasticity fields.")
	return SingleMappingDefinition.new(
		morphology_cached,
		scalar_used,
		psp_multiplier,
		plasticity,
		plasticity_constant_used,
		LTP_multiplier_used,
		LTD_multiplier_used,
		plasticity_window_used,
		delay_from_rule,
	)


static func _from_FEAGI_JSON_dict_rule(mapping_property: Dictionary) -> SingleMappingDefinition:
	var morph_id: Variant = mapping_property.get("morphology_id", null)
	if morph_id == null:
		push_error("SingleMappingDefinition: mapping dict missing morphology_id")
		return null
	var morphology_cached: BaseMorphology = _get_cached_morphology_for_mapping_rule(morph_id)
	if morphology_cached == null:
		return null
	var raw_scalar: Variant = mapping_property.get("morphology_scalar", null)
	var scalar_used: Vector3i
	if raw_scalar == null:
		scalar_used = DEFAULT_POSITIVE_SCALAR
	else:
		scalar_used = _safe_convert_to_vector3i(raw_scalar, "morphology_scalar")
	# Genome / API may omit keys; align with connectome defaults (e.g. plasticity_flag unwrap_or(false))
	var psp_multiplier: float = float(mapping_property.get("postSynapticCurrent_multiplier", DEFAULT_PSP_MULTIPLIER))
	var plasticity: bool = bool(mapping_property.get("plasticity_flag", DEFAULT_PLASTICITY))
	if morphology_cached.name == &"associative_memory":
		plasticity = true
	var delay_parsed: int = maxi(1, int(mapping_property.get("synaptic_delay_bursts", DEFAULT_SYNAPTIC_DELAY_BURSTS)))
	if !plasticity:
		return SingleMappingDefinition.new(
			morphology_cached,
			scalar_used,
			psp_multiplier,
			plasticity,
			DEFAULT_PLASTICITY_CONSTANT,
			DEFAULT_LTP_MULTIPLIER,
			DEFAULT_LTD_MULTIPLIER,
			DEFAULT_PLASTICITY_WINDOW,
			delay_parsed,
		)
	var plasticity_constant_used: float = float(mapping_property.get("plasticity_constant", 0.0))
	var LTP_multiplier_used: float = float(mapping_property.get("ltp_multiplier", 0.0))
	var LTD_multiplier_used: float = float(mapping_property.get("ltd_multiplier", 0.0))
	var plasticity_window_used: int = int(mapping_property.get("plasticity_window", DEFAULT_PLASTICITY_WINDOW))
	# R-STDP optional fields. plasticity_mode arrives as a string ("off"|"stdp"|"rstdp"); when
	# absent we leave the field empty and let downstream code infer the legacy STDP path.
	var plasticity_mode_raw: Variant = mapping_property.get("plasticity_mode", "")
	var plasticity_mode_used: String = String(plasticity_mode_raw).to_lower() if plasticity_mode_raw != null else ""
	var eligibility_decay_used: int = int(mapping_property.get("eligibility_decay_bursts", 0))
	var reward_area_used: String = String(mapping_property.get("reward_source_area", ""))
	var punishment_area_used: String = String(mapping_property.get("punishment_source_area", ""))
	var defn := SingleMappingDefinition.new(
		morphology_cached,
		scalar_used,
		psp_multiplier,
		plasticity,
		plasticity_constant_used,
		LTP_multiplier_used,
		LTD_multiplier_used,
		plasticity_window_used,
		delay_parsed,
	)
	defn._plasticity_mode = plasticity_mode_used
	defn._eligibility_decay_bursts = eligibility_decay_used
	defn._reward_source_area = reward_area_used
	defn._punishment_source_area = punishment_area_used
	return defn


## Given a mapping rule from FEAGI (object form or legacy array row) creates a [SingleMappingDefinition] object
static func from_FEAGI_JSON(mapping_property: Variant) -> SingleMappingDefinition:
	if mapping_property is Array:
		return _from_FEAGI_JSON_array_rule(mapping_property as Array)
	if mapping_property is Dictionary:
		return _from_FEAGI_JSON_dict_rule(mapping_property as Dictionary)
	push_error("SingleMappingDefinition: mapping rule must be Array or Dictionary, got %s" % type_string(typeof(mapping_property)))
	return null


## Given an array of mapping rules from FEAGI (objects and/or legacy arrays), output [SingleMappingDefinition]s
static func from_FEAGI_JSON_array(mapping_rules: Array) -> Array[SingleMappingDefinition]:
	var output: Array[SingleMappingDefinition] = []
	for rule in mapping_rules:
		var mapping := SingleMappingDefinition.from_FEAGI_JSON(rule)
		if mapping == null:
			continue
		output.append(mapping)
	return output

## Returns an array of the [SingleMappingDefinition] objects as FEAGI formatted dictionaries
static func to_FEAGI_JSON_array(input_mappings: Array[SingleMappingDefinition]) -> Array[Dictionary]:
	var output: Array[Dictionary] = []
	for mapping: SingleMappingDefinition in input_mappings:
		if mapping.is_morphology_valid():
			output.append(mapping.to_FEAGI_JSON())
		else:
			push_error("Exporting SingleMappingDefinition that has a null morphology. These placeholders will be skipped in the export in an attempt at stability, but this should never happen!")
	return output

## Returns an array with no duplicates of all morphologies within an array of [SingleMappingDefinition]
static func get_involved_morphologies(input_mappings: Array[SingleMappingDefinition]) -> Array[ BaseMorphology]:
	var morphologies_involved: Array[BaseMorphology] = []
	for mapping: SingleMappingDefinition in input_mappings:
		if !(mapping.morphology_used in morphologies_involved):
			morphologies_involved.append(mapping.morphology_used)
	return morphologies_involved


## Create Object
##
## R-STDP fields are optional and default to "unset" (empty string / 0). When all four
## R-STDP params are left at their defaults, the resulting object behaves exactly like
## a legacy STDP definition: to_FEAGI_JSON() omits them and consumers fall back to the
## STDP path. This keeps the constructor backward compatible with all existing callers.
func _init(
	morphology: BaseMorphology,
	positive_scalar: Vector3i,
	psp_multilpier: float,
	plasticity: bool,
	plasticity_constant_: float = DEFAULT_PLASTICITY_CONSTANT,
	ltp_multiplier: float = DEFAULT_LTP_MULTIPLIER,
	ltd_multiplier: float = DEFAULT_LTD_MULTIPLIER,
	plasticity_window_: int = DEFAULT_PLASTICITY_WINDOW,
	synaptic_delay_bursts_: int = DEFAULT_SYNAPTIC_DELAY_BURSTS,
	plasticity_mode_: String = "",
	eligibility_decay_bursts_: int = 0,
	reward_source_area_: String = "",
	punishment_source_area_: String = "",
):
	_morphology_used = morphology
	_scalar = positive_scalar
	_post_synaptic_current_multiplier = psp_multilpier
	_plasticity_flag = plasticity
	if _morphology_used != null and _morphology_used.name == &"associative_memory":
		_plasticity_flag = true
	_plasticity_constant = plasticity_constant_ # not sure how to better segregate this name. Too Bad!
	_LTP_multiplier = ltp_multiplier
	_LTD_multiplier = ltd_multiplier
	_plasticity_window = plasticity_window_
	_synaptic_delay_bursts = maxi(1, synaptic_delay_bursts_)
	_plasticity_mode = plasticity_mode_.to_lower()
	_eligibility_decay_bursts = maxi(0, eligibility_decay_bursts_)
	_reward_source_area = reward_source_area_
	_punishment_source_area = punishment_source_area_

## Returns a dictionary of this object in the same format FEAGI expects
func to_FEAGI_JSON() -> Dictionary:
	var associative_memory: bool = _morphology_used != null and _morphology_used.name == &"associative_memory"
	if !_plasticity_flag and !associative_memory:
		return {
			"morphology_id": _morphology_used.name,
			"morphology_scalar": FEAGIUtils.vector3i_to_array(_scalar),
			"postSynapticCurrent_multiplier": _post_synaptic_current_multiplier,
			"plasticity_flag": _plasticity_flag,
			"synaptic_delay_bursts": int(_synaptic_delay_bursts),
		}
	else:
		var out: Dictionary = {
			"morphology_id": _morphology_used.name,
			"morphology_scalar": FEAGIUtils.vector3i_to_array(_scalar),
			"postSynapticCurrent_multiplier": _post_synaptic_current_multiplier,
			"plasticity_flag": true,
			"plasticity_constant": _plasticity_constant,
			"ltp_multiplier": _LTP_multiplier,
			"ltd_multiplier": _LTD_multiplier,
			"plasticity_window": int(_plasticity_window),
			"synaptic_delay_bursts": int(_synaptic_delay_bursts),
		}
		if _plasticity_mode != "":
			out["plasticity_mode"] = _plasticity_mode
		if _eligibility_decay_bursts > 0:
			out["eligibility_decay_bursts"] = _eligibility_decay_bursts
		if _reward_source_area != "":
			out["reward_source_area"] = _reward_source_area
		if _punishment_source_area != "":
			out["punishment_source_area"] = _punishment_source_area
		return out

## Returns if the morphology is not null and if it is found in the morphology cache
func is_morphology_valid() -> bool:
	if _morphology_used == null:
		return true
	return _morphology_used.name in FeagiCore.feagi_local_cache.morphologies.available_morphologies.keys()

## Is this a memory mapping (does it use the episodic_memory morphology)
func is_memory_mapping() -> bool:
	if _morphology_used == null:
		return false
	return _morphology_used.name == &"episodic_memory" # TODO this needs to be a reference
