name: "Bridge Update Version and push to HUB"

on:
  push:
    branches:
      - staging
    paths:
      - 'src/bridge_godot_python.py'
      - 'src/configuration.py'
  workflow_dispatch:


 
jobs:
  bridge_version:
    name: Bridge Update Version
    runs-on: ubuntu-20.04
    if: github.repository == 'feagi/brain-visualizer' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge in New Changes
        run: |
          # Set up Git
          git config --global user.name "BrainVisualizerPushAction"
          git config --global user.email "BrainVisualizerPushAction@neuraville.com"
          git config --global --add safe.directory /__w/brain-visualizer/brain-visualizer
          echo "set vars"
          git checkout -b temp
          
      - name: Set Compile Time
        run: |
          cd src
          ./version_generate.sh
      - name: Push version changes
        run: |
          git add .
          git commit -m "Updated Version"
          echo "committed"
          git push origin temp:pre-release --force
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          tags: neuraville/bridge:latest
          
          
