name: Contribute to public BV

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - pre-pub-staging

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        repository: feagi/brain-visualizer
        token: ${{ secrets.PUBLIC_PAT_MNT }}

    - name: Generate branch name
      run: echo "BRANCH_NAME=neuraville-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

    - name: Checkout or create neuraville branch
      run: |
        git checkout $BRANCH_NAME || git checkout -b $BRANCH_NAME

    - name: Setup Git with PAT and commit changes
      run: |
        git config --global user.email "dev@neuraville.com"
        git config --global user.name "NeuravilleDeveloper"
        git remote add public https://github.com/feagi/brain-visualizer.git
        git diff --exit-code || git commit -m "Sync with pre-pub-staging excluding .env and .github directory changes"
        git push public ${{ env.BRANCH_NAME }} --force
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_PAT_MNT }}

    - name: Debug branch name
      run: echo Branch name is ${{ env.BRANCH_NAME }}

    - name: Create PR using GitHub CLI
      run: |
        # Set up GitHub CLI
        gh auth login --with-token <<< "${{ secrets.PUBLIC_PAT_MNT }}"
        
        # Create a pull request
        gh pr create \
          --repo feagi/brain-visualizer \
          --base staging \
          --head ${{ env.BRANCH_NAME }} \
          --title "Updates from Neuraville Inc" \
          --body "This PR syncs with latest Neuraville Inc. development code."
      env:
        GH_CLI_TOKEN: ${{ secrets.PUBLIC_PAT_MNT }}

