name: "Brain Visualizer Web Export"

on:
  workflow_dispatch

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: Web


 
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Merge in New Changes
        run: |
          # Set up Git
          git config --global user.name "BrainVisualizerPushAction"
          git config --global user.email "BrainVisualizerPushAction@neuraville.com"
          git config --global --add safe.directory /__w/brain-visualizer/brain-visualizer
          echo "set vars"
          git fetch --all
          git merge origin/staging --allow-unrelated-histories
          
        
      - name: Setup for Build
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      
      - name: Create Build Directory
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          
      - name: Set Compile Time
        run: |
          chmod +x ./set_timestamp.sh
          ./set_timestamp.sh
      - name: Web Build
        run: |
          godot -v --rendering-driver opengl3 --headless --export-release "HTML5" /__w/brain-visualizer/brain-visualizer/html/index.html
      - name: Push Web Export
        run: |
          git add .
          git commit -m "Updated Web Export"
          echo "committed"
          git push origin/main
          
          
