name: "Update bridge or/and BV versions"

on:
  push:
    branches:
      - staging
    paths:
      - 'godot_source/**'
      - 'src/bridge_godot_python.py'
      - 'src/configuration.py'
  workflow_dispatch:

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: Web

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    if: github.repository == 'feagi/brain-visualizer'
    container:
      image: neuraville/godot_export_web:v4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge in New Changes
        run: |
          # Set up Git
          git config --global user.name "BrainVisualizerPushAction"
          git config --global user.email "BrainVisualizerPushAction@neuraville.com"
          git config --global --add safe.directory /__w/brain-visualizer/brain-visualizer
          echo "set vars"
          git fetch origin
          git checkout -b temp

      - name: Create Build Directory
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH

      - name: Set Compile Time
        run: |
          chmod +x ./set_timestamp.sh
          ./set_timestamp.sh
      - name: Web Build
        run: |
          ls && pwd
          cd godot_source
          /root/Godot_v4.1.1-stable_linux.x86_64 --headless --export-release Web ../html/index.html
          cd ..
          echo "CHECKING HTML FILES"
          pwd
          ls
      - name: Push Web Export
        run: |
          git add .
          git commit -m "Updated Web Export"
          echo "committed"
          git push origin temp:pre-release
